name: Update helpwindow images

on:
  push:
    branches: 
      - dev
    paths:
      - docs/images

jobs:
  update-images:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev repository
        uses: actions/checkout@v4
        with:
          ref: dev
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - name: Update images
        run: |
          python ./scripts/update_helpwindow_imgs.py
      - name: commit and push
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git add btd6bot/Files/helpwindow/images
          git commit -m "Update images"
          git push