name: Ruff linting

on: [push, pull_request]
  branches: 
    - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: 3.x
 
    steps:
      - name: Checkout dev repository
        with:
          ref: dev
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Lint codebase with ruff
        run: |
          ruff check